# Generated by Django 6.0 on 2025-12-03 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=2048)),
                ("slug", models.CharField(db_index=True, max_length=16, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("clicks", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
